prefix/rplidar_node:
  ros__parameters:
    angle_compensate: false
    channel_type: serial
    flip_x_axis: false
    frame_id: prefix/scan
    inverted: false
    scan_mode: Sensitivity
    serial_baudrate: 256000  #A1 115200 A3 256000
    serial_port: /dev/ttyUSB0
    tcp_ip: 192.168.0.7
    tcp_port: 20108
    topic_name: scan
    use_sim_time: false

